// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQV1xWtybzy7601ueGCJl4CiUnbSvjVvA',
    appId: '1:930730541980:web:39a9fe9213145c6ddd7e59',
    messagingSenderId: '930730541980',
    projectId: 'samasante-5ddbe',
    authDomain: 'samasante-5ddbe.firebaseapp.com',
    storageBucket: 'samasante-5ddbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDAn7EQxOanuCLmtgcJ7G-shfcLTwlnRE',
    appId: '1:930730541980:android:920e4300995a5dffdd7e59',
    messagingSenderId: '930730541980',
    projectId: 'samasante-5ddbe',
    storageBucket: 'samasante-5ddbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1D1wKDY1WkgThaoCD5a9fU4u8qisifRI',
    appId: '1:930730541980:ios:154750d4bfe2013cdd7e59',
    messagingSenderId: '930730541980',
    projectId: 'samasante-5ddbe',
    storageBucket: 'samasante-5ddbe.firebasestorage.app',
    iosBundleId: 'com.example.samaSante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1D1wKDY1WkgThaoCD5a9fU4u8qisifRI',
    appId: '1:930730541980:ios:154750d4bfe2013cdd7e59',
    messagingSenderId: '930730541980',
    projectId: 'samasante-5ddbe',
    storageBucket: 'samasante-5ddbe.firebasestorage.app',
    iosBundleId: 'com.example.samaSante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQV1xWtybzy7601ueGCJl4CiUnbSvjVvA',
    appId: '1:930730541980:web:3ba0bc1aa78f1110dd7e59',
    messagingSenderId: '930730541980',
    projectId: 'samasante-5ddbe',
    authDomain: 'samasante-5ddbe.firebaseapp.com',
    storageBucket: 'samasante-5ddbe.firebasestorage.app',
  );
}
